Ft test pull request #1
Grifo89/ruby-tic-tac-toe pull request #8
Opened 2019-11-12 21:20 UTC by Grifo89

Hey, I'm ready to have a review. Thanks.

2019-11-13 05:05 UTC, whiz25 requested changes
## Nice work with the tests :+1: 
You have implemented some test cases and they all pass. However, the your coverage is low. This project is supposed to include test cases for both the ```tic tac toe``` game and the ```enumerables``` projects as described [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/). I only see tests for the ```tic tac toe```. May I know why?

#### Please add more tests and re-submit for another review.

### Martin Afani

2019-11-13 05:06 UTC, whiz25 reviewed
Before I forget, please fix the conflicts you have in your files.

2019-11-13 19:46 UTC, Grifo89 commented
@whiz25 those are different projects, this one is for tic-tac-toe and I implemented the tests required by Odin which are the same for Pathwright.

2019-11-14 04:51 UTC, maelfosso requested changes
# Changes required

Hello @Grifo89 @whiz25 ,

The code is improved. Nice :+1: 
However it's still not good.

1.
```ruby
class Board1 < Board
        private def default_grid
          [[1, 2, 3], %w[X X X], [7, 8, 9]]
        end
      end
      board1 = Board1.new
```
That is really not a good practice. Not at all !!! Read the comment to know how to solve it.

2. You just wrote tests for checking the **game_over?** method. What about the other **public** methods like `set_cell`, `convert_input` for example from `Board` class ? `Handlers` class ? `Player` class ? You are not obliged to write the tests for all the methods but show us that most of your public method are well working.

Kindly make the changes and submit a new code review request
Thanks

**Mael FOSSO**
[Github](https://github.com) | [Twitter](https://twitter.com) | [LinkedIn](https://www.linkedin.com/in/mael-elvis-fosso-650b6346/)

2019-11-14 04:51 UTC, maelfosso commented on spec/tic_tac_toe_spec.rb
> +  end
Simpy do 
```ruby
let(:player) { Player.new('X', 'Christian') }
```

2019-11-14 04:51 UTC, maelfosso commented on spec/tic_tac_toe_spec.rb
> +      end
Not Good !!!
I do not know if you noticed that this block, I mean the creation of that class, slowed the execution of the test
Changed it everywhere in your code to this
```ruby
allow_any_instance_of(Board).to receive(:default_grid).and_return([%w[X X X], [4, 5, 6], [7, 8, 9]])
board1 = Board.new
```
After change run the tests. Not only is it a good practice but it's faster.

2019-11-14 15:51 UTC, Grifo89 commented on spec/tic_tac_toe_spec.rb
> +  end
Hey, I was aware of that, but I didn't think it could be a big deal anyway I'm gonna change it.

2019-11-14 16:04 UTC, Grifo89 commented on spec/tic_tac_toe_spec.rb
> +      end
What you are saying doesn' t make sense. Are you saying that I have to become a private method which turns out to be the initial state to a public one and allow it to receive arguments just to make the test more efficient? and also I was searching if actually what I did is classified as bad  practice and I didn't find anything saying that, so if you have a more efficient way to test a private method which doesn't have any parameters please show me how to do it and also back it up what you are saying about bad practice or you can give me the approval, otherwise I'll have to reach out the success team because if you don't know a better way  you are just making things up.

2019-11-14 16:11 UTC, Grifo89 commented
Hey everybody, well It seems you guys may have lack of humbleness in some cases and just to believe that you know more because you're TSE's it makes you make mistakes then if you can't back it up what you are saying with resources and if you carry on like this I'm gonna ask for help to the success team.

2019-11-15 02:14 UTC, Ispirett requested changes
## status: changes required :1st_place_medal: 
Hey great work @Grifo89  @whiz25 ,   :+1:  :100:  so far just some small changes

I lett some comments bellow.

you  can read up on best testing practices here [read](https://anthonysciamanna.com/2016/02/14/should-private-methods-be-tested.html)

2019-11-15 02:14 UTC, Ispirett commented on spec/tic_tac_toe_spec.rb
> +end
Its convention to only test public-facing methods.
A better approach would be to use public methods to update the game state. 
**[example]**
```
player = Player.new('X', 'tom')
newBoard =  Board.new
newBoard.set_cell(player, 5)
newBoard.set_cell(player, 1)
```
you can use this approach to set the state of the board in a step like pattern like this.
this better mimics how the game will be played also

2019-11-18 15:21 UTC, Grifo89 commented on spec/tic_tac_toe_spec.rb
> +end
Thank you for bothering you and explain to me another approach.

2019-11-18 18:45 UTC, whiz25 approved these changes
### Good job :clap: 
It's a :+1: from me. Go ahead and merge. 

### Martin Afani

2019-11-18 19:59 UTC, merged